//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.02 at 03:28:36 PM IST 
//


package com.pradeep.course_details;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CourceDetails" type="{http://www.pradeep.com/course-details}CourceDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courceDetails"
})
@XmlRootElement(name = "GetCourceDeatilsResponse")
public class GetCourceDeatilsResponse {

    @XmlElement(name = "CourceDetails", required = true)
    protected CourceDetails courceDetails;

    /**
     * Gets the value of the courceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CourceDetails }
     *     
     */
    public CourceDetails getCourceDetails() {
        return courceDetails;
    }

    /**
     * Sets the value of the courceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourceDetails }
     *     
     */
    public void setCourceDetails(CourceDetails value) {
        this.courceDetails = value;
    }

}
